on:
  workflow_dispatch:
  push:
    branches: main
  
name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install PlantUML.jar
        uses: wei/wget@v1
        with:
          args: -O plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2022.6/plantuml-1.2022.6.jar

      - name: Set PLANTUML environment
        run: export PLANTUML=./plantuml.jar

      - name: install Graphviz
        uses: tlylt/install-graphviz@v1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: tutoriel-famixtypescript.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}